version: '3'

networks:
  backend:
    driver: "bridge"

services:
  pgsql:
    image: postgres:12.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hmvc
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
